services:
  push-nuget:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: push-nuget
  build:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
  test:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
  # Run with: `docker compose run codecov-uploader {codecov-token}`
  codecov-uploader:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: codecov-uploader
