FROM mcr.microsoft.com/dotnet/sdk:7.0-bullseye-slim

ARG version  
WORKDIR /sln

COPY . .

RUN dotnet restore
RUN dotnet build /p:Version=$version -c Release --no-restore  
RUN dotnet pack /p:Version=$version -c Release --no-restore --no-build -o /sln/artifacts 

ENTRYPOINT ["dotnet", "nuget", "push", "/sln/artifacts/*.nupkg", "--source", "https://api.nuget.org/v3/index.json"]
