name: 'Push NuGet'

on:
  
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
  test:
    uses: ./.github/workflows/reusable-test.yml
    needs: build
  push-nuget:
    name: Push nuget package
    needs: test
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker compose build --build-arg version="$GITHUB_REF_NAME" push-nuget
      - name: Push the package
        run: docker compose run --rm push-nuget --api-key $NUGET_API_KEY
