name: 'Test'

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker-compose build test
      - name: Run tests in docker image
        run: docker-compose run test
      - name: Get Codecov env
        id: get-codecov-env
        run: echo "ci_env=`bash <(curl -s https://codecov.io/env)`" >> "$GITHUB_OUTPUT"
      - name: Upload coverage reports to Codecov
        run: |
          echo $CODECOV_TOKEN
          docker-compose run $ci_env -e CI=true codecov-uploader $CODECOV_TOKEN
        env:
          ci_env: ${{ steps.get-codecov-env.outputs.ci_env }}
          CODECOV_TOKEN: asd
